# Generated by Django 3.1.3 on 2020-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('bid', models.IntegerField()),
                ('Image', models.URLField()),
                ('Description', models.TextField()),
                ('Category', models.CharField(choices=[['F', 'Fashion'], ['H', 'Home'], ['E', 'Electrical'], ['T', 'Toys'], ['Elec', 'Electronics']], max_length=10)),
            ],
        ),
    ]
