# Generated by Django 3.1.3 on 2020-11-16 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_create_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='create_listing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='create_listing',
            name='bid',
            field=models.PositiveIntegerField(),
        ),
    ]
