# Generated by Django 3.1.3 on 2020-11-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
